version: '3.8'

services:
  # Postgresql
  joomla-postgres:
    image: postgres:15.3-alpine
    container_name: joomla-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=102030
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data/pg:/var/lib/postgresql/data
      
  
  # PG Admin 
  joomla-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: joomla-pgadmin
    restart: always
    depends_on:
      - joomla-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@local.com
      PGADMIN_DEFAULT_PASSWORD: 102030
    ports:
      - "8080:80"
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin

  # Redis
  joomla-redis:
    image: redis
    container_name: joomla-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/data
    command: redis-server --appendonly yes

  # PHP 
  joomla-php:
    build: ./docker/php    
    container_name: joomla-php
    volumes:
      - ./www:/www
    environment:
      - SESSION_HANDLER=redis
      - SESSION_PATH=tcp://redis:6379?auth=${REDIS_PASSWORD}
      - SESSION_MAX_TIME_LIFE=86400

  
  # NGINX
  dcs-nginx: 
    image: nginx
    container_name: joomla-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./src:/www

networks:
  default:
    name: local-network
    