version: '3.8'

services:
  # Postgresql
  joomla-postgres:
    image: postgres:15.3-alpine
    container_name: joomla-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=102030
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - local-network
      
  
  # PG Admin 
  joomla-pgadmin:
    image: dpage/pgadmin4
    container_name: joomla-pgadmin
    restart: always
    depends_on:
      - joomla-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@local.com"
      PGADMIN_DEFAULT_PASSWORD: "102030"
    ports:
      - 8000:80
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    networks:
      - local-network

  # Redis
  joomla-redis:
    image: redis
    container_name: joomla-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-volume:/data
    command: redis-server --appendonly yes 
    networks:
      - local-network

  # PHP 
  joomla-php:
    build: ./docker/php    
    container_name: joomla-php
    volumes:
      - ./src:/var/www/html
    environment:
      - SESSION_HANDLER=redis
      - SESSION_PATH=tcp://redis:6379
      - SESSION_MAX_TIME_LIFE=86400
    links:
      - joomla-redis
    networks:
      - local-network

  
  # NGINX
  joomla-nginx: 
    image: nginx:latest
    container_name: joomla-nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./src:/var/www/html
    links:
      - joomla-php
    networks:
      - local-network

networks:
  local-network:
    driver: bridge

volumes:
  postgres-volume:
    external: false
  pgadmin-volume:
    external: false
  redis-volume:
    external: false